.git/
.idea/
.vs/
.vscode/
cmake-build-*/
out/

build/

.vcpkg-downloads/
.vcpkg-cache/

third_party/vcpkg/buildtrees/
third_party/vcpkg/packages/
third_party/vcpkg/downloads/

**/*.log
**/CMakeUserPresets.json
